name: wallet_connect
description: Wallet Connect client made in love with dart.
version: 1.0.4
homepage: https://github.com/Orange-Wallet/wallet-connect-dart

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  hex: ^0.2.0
  web_socket_channel: ^2.4.0
  uuid: ^4.0.0
  http: ^1.1.2
  cryptography: ^2.0.5
  convert: ^3.1.1
  collection: ^1.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
